### ISSUE TITLE
websocket securty bağlantı problemi

### ISSUE THREAD

**Issue by superquantum** [icrypex-com/apidoc#10]
Merhba. websocket ile Authentication işlemini bir türlü tamamlayamıyorum. request ile problemsiz bağlanıyor ama ws. problem çıkıyor.Örnek kodlara ya da Signature (HMAC) konusunda imzayla ilgili desteğe ihtiyacım var. teşekkür ederim.

api-login|{"pk":"v3rfsc....cS9TB","s":"mJhsg...mI81g=","ts":1689059811000,"n":15000}
Authentication sent
Authentication response: api-auth|{"v":false}

**Comment by mhelvacikoylu** [comment]
Merhaba,

Oluşturduğunuz API Key'de herhangi bir IP tanımladınız mı?
Tanımladığınız IP Adresinden mi bağlanıyorsunuz?
API Key'e WebSocket bağlantı yetkisi tanımladınız mı?

**Comment by superquantum** [comment]
Merhaba Mehmet Bey

İp tanımlı değil fakat apiye  websocket bağlı. Eğer auth için ip zorunlu ise tekrar denerim.
________________________________

**Comment by superquantum** [comment]
Merhaba Mehmet Bey.
ip tanımlamasını daha önce de yapmıştım ama tekrar denedim. maalefe. auth olmak istediğimde verileri aşağıdaki kodlarda görüleceği üzere verileri verdiğimde maalsef sunucudan cevap dönmüyor. bende mi hata var anlamadım. size birebir kullandığım kodlarımı gönderiyorum. acaba hata bende mi? bendeyse nerede. yardımcı olabilir misiniz? çok teşekkürler.



import hashlibimport hmacimport jsonimport timeimport websocket
public_key = ".."private_key = ".."

websocket_url = "wss://istream.icrypex.com"
zaman = int(time.time() * 1000)nonce = 15000  # message = f'api-login|{{"pk":"{public_key}","s":"{private_key}","ts":{zaman},"n":{nonce}}}'signature = hmac.new(private_key.encode(), message.encode(), hashlib.sha256).hexdigest()
auth_message = f'api-login|{{"pk":"{public_key}","s":"{signature}","ts":{zaman},"n":{nonce}}}'
def on_open(ws):    print("ws bağlantı kuruldu")    ws.send(auth_message)
def on_message(ws, message):    print(f"Alınan Mesaj: {message}")
def on_error(ws, error):    print(f"ws hata: {error}")
def on_close(ws):    print("ws bağlantısı kapandı")
ws = websocket.WebSocketApp(websocket_url,                            on_open=on_open,                            on_message=on_message,                            on_error=on_error,                            on_close=on_close)
ws.run_forever()



 

    14 Temmuz 2023 Cuma 15:02:41 GMT+3 tarihinde, Mustafa T. CANBAY ***@***.***>şunu yazdı:  
 
 Merhaba Mehmet Bey 
İp tanımlı değil fakat apiye  websocket bağlı. Eğer auth için ip zorunlu ise tekrar denerim. From: Mehmet Helvacıköylü ***@***.***>
Sent: Friday, July 14, 2023 1:01:46 PM
To: icrypex-com/apidoc ***@***.***>
Cc: superquantum ***@***.***>; Author ***@***.***>
Subject: Re: [icrypex-com/apidoc] websocket securty bağlantı problemi (Issue #10) 


Merhaba,

Oluşturduğunuz API Key'de herhangi bir IP tanımladınız mı?
Tanımladığınız IP Adresinden mi bağlanıyorsunuz?
API Key'e WebSocket bağlantı yetkisi tanımladınız mı?

**Comment by mhelvacikoylu** [comment]
Merhaba,

Sanırım problem signature oluşturma ile ilgili.
**hmac.new** fonksiyonunun ikinci parametresine tüm mesajın içeriğini girmişsiniz. Ancak buraya public key ile timestamp gönderilmesi gerekiyor. Örnek olarak şu şekilde olmalı:

```python
data = "{}{}".format(public_key, zaman).encode('utf-8')
signature = hmac.new(private_key.encode(), data, hashlib.sha256).hexdigest()
```

**Comment by superquantum** [comment]
import asyncioimport websocketsimport jsonimport hmacimport hashlib ,time
async def authenticate_websocket():    uri = "wss://istream.icrypex.com"
    async with websockets.connect(uri) as websocket:        public_key = "..."        private_key = "..."        zaman = str(int(time.time() * 1000))        auth_data = "{}{}".format(public_key, zaman).encode('utf-8')        signature = hmac.new(private_key.encode(), auth_data, hashlib.sha256).hexdigest()        auth_message = "api-login|{{\"pk\":\"{}\",\"s\":\"{}\",\"ts\":{},\"n\":{}}}".format(public_key, signature, zaman, 15000)        await websocket.send(auth_message)        while True:            response = await websocket.recv()            print("Alınan mesaj:", response)asyncio.run(authenticate_websocket())


Merhaba Mehmet Bey.
ip kayıtlı ws api üzerinde açık olmasına rağmen bağlantı sağlayınca eğer doğru bağlantı yapmışsam sunucudan cevap alamıyorum. tickers sorunsuz çalışıyor. ama bunlar sıkıntılı. yarıdımcı olursanız sevinirim. acaba serverler de mi bir sorun var? kodları test edin. hatalı keyleri verince false dönüyor. fakat doğru girince hiçbir yanıt gelmiyor. bekliyor.

 

    18 Temmuz 2023 Salı 14:06:22 GMT+3 tarihinde, Mehmet Helvacıköylü ***@***.***>şunu yazdı:  
 
 


Merhaba,

Sanırım problem signature oluşturma ile ilgili.
hmac.new fonksiyonunun ikinci parametresine tüm mesajın içeriğini girmişsiniz. Ancak buraya public key ile timestamp gönderilmesi gerekiyor. Örnek olarak şu şekilde olmalı:
data = "{}{}".format(public_key, zaman).encode('utf-8')
signature = hmac.new(private_key.encode(), data, hashlib.sha256).hexdigest()

**Comment by Quanthss** [comment]
Merhaba, Ben de aynı sorunla karşılaştım. "User Order Trade" başlığı altındaki websocket bağlantısını bir türlü kuramadım.Server tarafında bir sorun olabilir mi? Ya da mümkünse doğru olduğundan emin olduğunuz bir kod parçası paylaşabilir misiniz?

**Comment by mhelvacikoylu** [comment]
Konu ile ilgili hata giderilmiştir.
