### ISSUE TITLE
Dokümantasyon Netleştirme

### ISSUE THREAD

**Issue by ErrorEater** [icrypex-com/apidoc#11]
> Orderbook Difference Message
> 3: The row is removed. There was a row with same price in previous snapshot but now all orders are canceled or filled.

Burada "q" verisi "0" mı dönüyor yoksa önceki değer mi?

> Last Trade Message
> s: Trade side 0 for buy, 1 for sell

Buradaki side kimin tarafını belirtiyor?
Market order gönderen takerı mı yoksa tahtada limit orderı beklemekte olan makerı mı?

**Comment by mhelvacikoylu** [comment]
> Burada "q" verisi "0" mı dönüyor yoksa önceki değer mi?

Eski değer dönüyor.

> Buradaki side kimin tarafını belirtiyor?
> Market order gönderen takerı mı yoksa tahtada limit orderı beklemekte olan makerı mı?

Yeni gelen market (limit olması da muhtemel) emrin yönünü. Başka bir deyişle trade tahtanın en iyi alış fiyatında gerçekleşiyorsa satış yönlü (yani 1), en iyi satış fiyatında gerçekleşiyorsa alış yönlü (yani 0) gönderilir.
