### ISSUE TITLE
Websocket Authentication Problem

### ISSUE THREAD

**Issue by emirhanyasin** [icrypex-com/apidoc#13]
Websocket uzerinden acoount position/trade updatelerini dinlemek icin authenticate olarak dinleme yapmaya calisirken, authentication sikintisi yasiyorum. 

Dokumanda belirtildigi uzere, authentication icin gonderilen string mesajinin icersinde apiKey, signature, timestamp ve nonce degerleri var. apiKey ve signature fieldlari icin submit_order yaparken gonderdigim ayni bilgileri yaziyorum string mesajinin icine. (submit_order yaparken herhangi bir sikinti yasamadan emir gonderebiliyorum, herhangi bir authentication vs error olmadan emir gonderiyor) timestamp ve nonce fieldlari icin de, belirtildigi uzere unix milisecond timestamp aliyorum ve nonce degeri olarak da 15000 ms giriyorum. Asagida son olarak websockete authentication icin gonderdigim ornek string mesajini gorebilirsiniz.

api-login|{"pk":"lOG9vU3iqYzB6LLtTxXWtqWLI5...","s":"3Vn0pfs+5nxsFwt...","ts":994152428,"n":15000}

Her mesaj gonderdigimde api-auth|{"v":false} mesaji donuyor. 

Sikintiyi cozmemde yardimci olabilirseniz sevinirim.

Tesekkurler

**Comment by mhelvacikoylu** [comment]
Kullandığınız API Key'in websocket yetkisini tanımladınız mı?

**Comment by emirhanyasin** [comment]
Evet. API restrictions altinda tum bolumler isaretli. (Wallet, Trade, Withdraw, Web Socket tum bu fieldlar gorunuyor sitede)

Ayrica girdigim bilgileri yazdigim fonksiyonlari asagida paylasiyorum.

```
std::string decode64(const std::string &val) {
    using namespace boost::archive::iterators;
    using It = transform_width<binary_from_base64<std::string::const_iterator>, 8, 6>;
    return boost::algorithm::trim_right_copy_if(std::string(It(std::begin(val)), It(std::end(val))), [](char c) {
        return c == '\0';
    });
}
```

```
std::string encode64(const std::string &val) {
    using namespace boost::archive::iterators;
    using It = base64_from_binary<transform_width<std::string::const_iterator, 6, 8>>;
    auto tmp = std::string(It(std::begin(val)), It(std::end(val)));
    return tmp.append((3 - val.size() % 3) % 3, '=');
}
```

```
std::string HMAC256(const std::string &key, const std::string &msg)
{
    unsigned char hash[EVP_MAX_MD_SIZE];
    unsigned int len;

    HMAC_CTX* ctx = HMAC_CTX_new(); 
    if (ctx == nullptr) {
        return "";
    }

    HMAC_Init_ex(ctx, key.data(), key.length(), EVP_sha256(), NULL);
    HMAC_Update(ctx, reinterpret_cast<const unsigned char*>(msg.data()), msg.length());
    HMAC_Final(ctx, hash, &len);

    HMAC_CTX_free(ctx);

    return std::string(reinterpret_cast<char*>(hash), len);
}
```

```
std::string getRequestSignature(std::string publicKey, std::string secretKey, unsigned long long timestamp)
{   

    std::string baseString_1 = publicKey + std::to_string(timestamp);
    std::string baseString = baseString_1;

    std::string decodedKey = decode64(secretKey);

    std::string signature = HMAC256(decodedKey, baseString);

    std::string base64Signature_1 = encode64(signature);
    std::string base64Signature = base64Signature_1;

    return base64Signature;
}
```

```
std::string createLoginString(const std::string& pk, const std::string& s, int64_t ts, int n) {
  std::string result = "api-login|{\"pk\":\"" + pk + "\",\"s\":\"" + s + "\",\"ts\":" + std::to_string(ts) + ",\"n\":" + std::to_string(n) + "}";
  return result;
}
```

```
milliseconds ms = duration_cast<milliseconds>(system_clock::now().time_since_epoch());
int currentTimeInMilliseconds = ms.count();

unsigned long long timestamp_sig = std::time(nullptr) * 1000;

string signature = getRequestSignature(publicKey, secretKey, timestamp_sig);

int nonce = 15000;

string output = createLoginString(publicKey, signature, currentTimeInMilliseconds, nonce);

ws.write(asio::buffer((std::string(output))));
```



Bu sekilde output mesajini olusturduktan sonra websocket baglantisina gonderiyorum ve her seferinde api-auth|{"v":false} donusu aliyorum.

**Comment by emirhanyasin** [comment]
Ayni sekilde signature create ederek gonderdigim submit_order requestlerinde bir sikinti yasamiyorum. Bu nedenle sikintinin timestamplerde oldugunu dusundum, bircok farkli sekilde timestamp basarak yolladim mesaji, ancak authetication basarili olmadi. Gonderdigim string mesajinin yapisinin da dogru oldugunu dusundum karsilastirdigimda.

**Comment by emirhanyasin** [comment]
Timestamp'i asagidaki gibi signature in icine verdigim timestamp ile ayni sekilde verdigimde,

```
unsigned long long timestamp_sig = std::time(nullptr) * 1000;
string signature = getRequestSignature(publicKey, secretKey, timestamp_sig);
int nonce = 15000;
string output = createLoginString(publicKey, signature, timestamp_sig, nonce);
ws.write(asio::buffer((std::string(output))));
```

bu sefer websocket baglantisi `api-auth|{"v":false}` mesaji da donmuyor. Websocketten hicbir donus almiyorum ve operation cancelled diyerek socket kapaniyor.

**Comment by emirhanyasin** [comment]
Bu sekilde bir timestamp ile gonderdigimde (tam olarak gonderdigim mesaj asagidadir) websocketten hicbir geri donus almiyorum. Yukarida belirttigim gibi `api-auth|{"v":false}` mesaji da gelmiyor.

`api-login|{"pk":"lOG9vU3iqYzB6LLtTxX...","s":"XPsj1eeXbxuhJTejGg7...","ts":1693218438000,"n":15000}`

**Comment by emirhanyasin** [comment]
Ayni kodun icersinde authentication mesajini,

```
unsigned long long timestamp_sig = std::time(nullptr) * 1000;
string signature = getRequestSignature(publicKey, secretKey, timestamp_sig);
int nonce = 15000;
string output = createLoginString(publicKey, signature, timestamp_sig, nonce);
```

bu sekilde gonderdigimde websocketten hicbir mesaj gelmiyorken,

```
unsigned long long timestamp_sig = std::time(nullptr) * 1000;
string signature = getRequestSignature(publicKey, secretKey, timestamp_sig);
int nonce = 15000;
string output = createLoginString(publicKey, signature, timestamp_sig/1000, nonce);
```

seklinde gonderdigimde (alinan timestamp'in 1000 ile carpilmamis hali) `api-auth|{"v":false}` hatasi donuyor.

Websocket serverinin hangi durumlarda bu `api-auth` mesajini gonderdigini aciklayabilirseniz sevinirim.

**Comment by emirhanyasin** [comment]
Sizin tarafinizdaki websocket serverinin loglarina bakabiliyorsaniz, gonderilen bu mesajlarin iceride nasil process edildigini soyleyebilirseniz sevinirim.

**Comment by mhelvacikoylu** [comment]
Konu ile ilgili tespit ettiğimiz bir hatayı düzelttik..
Probleminiz düzeldi mi? Tekrar deneyebilir misiniz?
