### ISSUE TITLE
API RATE LIMIT ISSUE

### ISSUE THREAD

**Issue by yuzgecoguz** [icrypex-com/apidoc#18]
API new order limiti 1 dakikada 1 kez atabilmekteyim.Neden düzeltmiyorsunuz bu sorunu

**Comment by yemreak** [comment]
@mhelvacikoylu

**Comment by mhelvacikoylu** [comment]
Merhabalar,
Müşteri temsilcilerimiz konu ile ilgili sizlerle görüştüğünü ve problemin çözüldüğünü ilettiler.

**Comment by yemreak** [comment]
Hayir problem cozulmedi, hala 1dk bir kez emir iletebiliyoruz, hic bir degisiklik olmadi, sadece gorusturler...
@mhelvacikoylu

**Comment by yuzgecoguz** [comment]
@mhelvacikoylu sorun çözülmedi hala devam etmekte. Sorun çözümü için elimden geldiğince katkıda bulunacağı mı da dile getirdim geri dönüş sağlanmadı.
