### ISSUE TITLE
v1/exchange/info

### ISSUE THREAD

**Issue by yuzgecoguz** [icrypex-com/apidoc#23]
https://api.icrypex.com/v1/exchange/info adresinde TRY paritesindeki veriler silinmiş. TRY piyasasında işlem yapmak yasak mı o zaman kaldırın pariteyi..

**Comment by akrepfatih** [comment]
icrypex.com global olduğu için TRY işlem çiftini kullanamaz. ( Yanlışım var ise düzeltin. )
icrypex.com.tr kullanabilir.
https://api.icrypex.com/v1/exchange/info
https://api.icrypex.com.tr/v1/exchange/info

**Comment by mhelvacikoylu** [comment]
> icrypex.com global olduğu için TRY işlem çiftini kullanamaz. ( Yanlışım var ise düzeltin. ) icrypex.com.tr kullanabilir. https://api.icrypex.com/v1/exchange/info https://api.icrypex.com.tr/v1/exchange/info

doğrudur. henüz github repository'lerde düzenleme yapılmadı. düzenleme yapıldıktan sonra iki borsa arasındaki kullanım farklarıyla ilgili tüm detaylara ulaşabileceksiniz.
