### ISSUE TITLE
bekir bey yönlendirdi.

### ISSUE THREAD

**Issue by satanxiety** [icrypex-com/apidoc#6]
botu çalıştırmakta sıkıntı yaşıyorum

**Comment by ehelvacikoylu** [comment]
Merhaba, ne gibi sıkıntı yaşıyorsunuz. Biraz detay verebilirseniz yardımcı olalım.

**Comment by satanxiety** [comment]
Bu api.icrypex.com sayfası bulunamıyor
Şu web adresi için web sayfası bulunamadı:https://api.icrypex.com/

HTTP ERROR 404

**Comment by akrepfatih** [comment]
https://api.icrypex.com/v1/orderbook?symbol=BTCUSDT
yukarıdaki şekilde bir işlem çiftinin tahtasını görebilirsiniz ve diğer public olan verilere rahatça ulaşabilirsiniz.
