### ISSUE TITLE
WebSocket Anlık İşlem Bilgisi Hk.

### ISSUE THREAD

**Issue by emin-karadag** [icrypex-com/apidoc#8]
Merhabalar,
Kripto para borsaları üzerinde al-sat yapan sistemime ICRYPEX borsasını da entegre etmek düşüncesindeyim. Ancak benim için önemli olan nokta şu ki: Market ve limit al-sat işlemlerinin Websocket üzerinden anlık alabiliyor olmam gerekiyor. Bireysel değil, genele açacağım bir yazılım olacak. Bu sebeple onlarca/yüzlerce üye için Rest API ile sürekli istek atıp sipariş durumlarını kontrol etmem efektif olmayacaktır.
Websocket üzerinden bu tarz bilgileri almak istiyorum. Bu noktadaki geliştirme planlarınızı benimle paylaşmanız mümkün müdür acaba?
Teşekkür ederim.

**Comment by mhelvacikoylu** [comment]
Merhaba.

Websocket dökümantasyonuna ilgili bölüm eklenmiştir.

https://github.com/icrypex-com/apidoc/blob/main/websockets.md#trade-channel
