### ISSUE TITLE
API Dokümantasyonu Güncellemeleri Hk.

### ISSUE THREAD

**Issue by emin-karadag** [icrypex-com/apidoc#9]
Merhaba,

API dokümantasyonunda herhangi bir güncelleme olduğunda (Örneğin; yeni bir endpiont eklendiğinde, bir endpoint'e yeni bir parametre eklendiğinde veya websocket yol haritasında bir ilerleme olduğunda vs.) geliştiriciler olarak haberdar olabileceğimiz bir mekanizma (github üzerinden olabilir, mail aboneliği üzerinden olabilir vs.) mevcut mudur?

Teşekkürler.

**Comment by mhelvacikoylu** [comment]
Proje sayfasının sağ üst bölümünde Watch'a tıklayıp All Activity'i seçebilirsiniz.
